PROMPT='%d'
PROMPT+=$'\n'"# "

export SHELL=/bin/zsh
export EDITOR=$(which nvim)
export PAGER=$(which less)
export MOLD_ROOT=$HOME/root_config

export XDG_DESKTOP_DIR="$HOME/Desktop"
export XDG_DOWNLOAD_DIR="$HOME/Downloads"
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_STATE_HOME="$HOME/.local/state"

mkdir -p $XDG_DESKTOP_DIR
mkdir -p $XDG_DOWNLOAD_DIR
mkdir -p $XDG_CONFIG_HOME
mkdir -p $XDG_CACHE_HOME
mkdir -p $XDG_DATA_HOME
mkdir -p $XDG_STATE_HOME

alias .="source"
alias e='nvim'
alias n='cd'
alias R='source ~/.zshrc'
alias ls='exa'
alias ll='ls -lah'
alias la='ls -la'
alias o='lf'
alias tree='exa --tree'
alias md='mkdir -p'
alias S="nvim +S"
alias F="nvim +F"
alias a="git add"
alias A="git add ."
alias s="git status"
alias c="git commit"
alias p="git push origin"
alias r="git remote -v"
alias ..="cd .."

alias xs="sudo xbps-query -Rs"
alias xq="sudo xbps-query"
alias xi="sudo xbps-install -y"
alias xr="sudo xbps-remove -R"

xu() {
  sudo xbps-install -Syu
  sudo xbps-reconfigure -fa
  sudo update-grub
}

# configrue zle
bindkey -v                           # enable vim mode
bindkey "^W" backward-kill-word      # ctl-w delete word backward insert mode
bindkey -a "^W" backward-kill-word   # ctl-w delete word backward normal mode
bindkey "^?" backward-delete-char    # delete key to work like normal
bindkey "^U" backward-kill-line      # ctl-u delete cur line insert mode
bindkey -a "^U" backward-kill-line   # ctl-u delete cur line normal mode
bindkey '^a' vi-beginning-of-line    # ctl a jumps to beginning of line insert mode
bindkey -a '^a' vi-beginning-of-line # ctl a jumps to beginning of line normal mode

bindkey -a '^g' vi-end-of-line       # cta s jumps to end of line normal mode
bindkey '^r' history-incremental-pattern-search-backward

bindkey -a 'n' down-line-or-history
bindkey -a 'e' up-line-or-history
bindkey -a 'y' vi-backward-char
bindkey -a 'o' vi-forward-char
bindkey -a 'Y' vi-beginning-of-line  # shift y jumps to beginning of lin in normal mode
bindkey -a 'O' vi-end-of-line        # shift o jumps to end of line in normal mode

bindkey -a 't' vi-find-next-char
bindkey -a 'T' vi-find-prev-char

bindkey -a "h" vi-repeat-find
bindkey -a 'H' vi-rev-repeat-find

bindkey -a 'f' vi-repeat-search
bindkey -a 'F' vi-rev-repeat-search

bindkey -a 'k' vi-yank
bindkey -a 'K' vi-yank-whole-line

bindkey -a 'w' vi-forward-word
bindkey -a 'W' vi-backward-word

bindkey -a 'E' vi-forward-word-end
bindkey -a 'J' vi-forward-blank-word-end
bindkey -a 'l' vi-open-line-below
bindkey -a 'L' vi-open-line-above

# C-x C-e edit this command in vim 
autoload -U edit-command-line
zle -N edit-command-line
bindkey '\C-x\C-e' edit-command-line

# [Shift - Tab] move through the completion menu backwards :)
if [[ "${terminfo[kcbt]}" != "" ]]; then
	bindkey "${terminfo[kcbt]}" reverse-menu-complete   # [Shift-Tab] - move through the completion menu backwards
fi

if [[ -d $HOME/.cargo ]];then 
  source $HOME/.cargo/env
fi
